#!/bin/bash
set -euxo pipefail

ssh -C icons.better-idea.org 'journalctl -u iconserver.service' > /tmp/icons.better-idea.stdout.txt
cat /tmp/icons.better-idea.stdout.txt | grep -B 4 -A 10 "http: panic serving"
