#!/bin/bash
set -euxo pipefail

ssh -C icons.better-idea.org 'journalctl -u iconserver.service' > /tmp/icons.better-idea.stdout.txt
cat /tmp/icons.better-idea.stdout.txt | egrep 'url=[^& ]*' -o > /tmp/urls
cat /tmp/urls | egrep '=((http|https)://)?[^=/]*' -o > /tmp/domains
cat /tmp/domains | sort | uniq -c | sort -nr | head -n 50

