package besticon

// PopularSites we might use for examples and testing.
var PopularSites []string

func init() {
	PopularSites = []string{
		"163.com",
		"about.com",
		"adobe.com",
		"alipay.com",
		"amazon.com",
		"amazonaws.com",
		"ameblo.jp",
		"apple.com",
		"bbc.co.uk",
		"bestbuy.com",
		"bing.com",
		"bongacams.com",
		"booking.com",
		"buzzfeed.com",
		"chase.com",
		"china.com",
		"cnet.com",
		"cnn.com",
		"coccoc.com",
		"craigslist.org",
		"dailymail.co.uk",
		"dailymotion.com",
		"dropbox.com",
		"ebay.com",
		"espn.go.com",
		"etsy.com",
		"ettoday.net",
		"facebook.com",
		"flickr.com",
		"flipkart.com",
		"github.com",
		"globo.com",
		"gmw.cn",
		"imdb.com",
		"imgur.com",
		"indiatimes.com",
		"instagram.com",
		"live.com",
		"mail.ru",
		"microsoft.com",
		"msn.com",
		"netflix.com",
		"nytimes.com",
		"odnoklassniki.ru",
		"outbrain.com",
		"paypal.com",
		"pinterest.com",
		"rakuten.co.jp",
		"reddit.com",
		"sina.com.cn",
		"stackoverflow.com",
		"t.co",
		"tumblr.com",
		"vimeo.com",
		"vk.com",
		"walmart.com",
		"wikia.com",
		"wikipedia.org",
		"wordpress.com",
		"xinhuanet.com",
		"yahoo.com",
		"yandex.ru",
		"yelp.com",
		"youku.com",
		"youtube.com",
	}
}
